name = "WOML"
uuid = "d1a85acf-acaa-4593-acac-c398b80e0e9d"
authors = ["William Manning <manning.w27@gmail.com>"]
version = "0.1.0"

[deps]
StructTypes = "856f2bd8-1eba-4b0a-8007-ebc267875bd4"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"

[compat]
julia = "^1.6"
